name: React Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Find Path
      run: |
        pwd
    - name: Install Dependencies
      run: |
        pwd
        cd backend
        pwd
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test
        python manage.py migrate

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies & build
      run: |
        pwd
        cd frontend
        pwd
        npm install
        npm run build
    - name: Find Build Content
      run: |
        cd /home/runner/work/react-django/react-django/frontend/build
        pwd
        ls
        cd /home
        pwd
        ls
